#!/usr/bin/env python3
"""
Convert a review export package into a YOLO detection dataset.

Input expected from tools/review_tools/build_review_indexes.py --export-package:
  export_YYYYMMDD_HHMMSS/exportable_metadata.jsonl

Each row should include at least:
  - image_path: full page image path, relative to project root
  - bbox: {x1, y1, x2, y2} in pixel coordinates on the page image
  - reviewed_type or type: class name

Output:
  output_dir/
  ├── images/train/*.jpg|png
  ├── images/val/*.jpg|png
  ├── labels/train/*.txt
  ├── labels/val/*.txt
  ├── data.yaml
  └── conversion_report.json
"""
from __future__ import annotations

import argparse
import hashlib
import json
import random
import shutil
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Tuple

from PIL import Image

DEFAULT_CLASSES = [
    "stamp",
    "handwritten_text",
    "typewritten_text",
    "crossout",
    "censorship_block",
    "table_fragment",
]


def read_jsonl(path: Path) -> Iterator[dict]:
    if not path.exists():
        raise FileNotFoundError(f"JSONL not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at {path}:{line_no}") from exc


def resolve_project_path(project_root: Path, raw_path: str | None) -> Path | None:
    if not raw_path:
        return None
    path = Path(raw_path)
    if path.is_absolute():
        return path
    return project_root / path


def safe_image_name(image_path: Path, index: int) -> str:
    digest = hashlib.sha1(str(image_path).encode("utf-8")).hexdigest()[:10]
    suffix = image_path.suffix.lower()
    if suffix not in {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tif", ".tiff"}:
        suffix = ".jpg"
    return f"page_{index:06d}_{digest}{suffix}"


def parse_bbox(row: dict) -> Tuple[float, float, float, float] | None:
    bbox = row.get("corrected_bbox") or row.get("bbox")
    if isinstance(bbox, dict):
        try:
            x1 = float(bbox["x1"])
            y1 = float(bbox["y1"])
            x2 = float(bbox["x2"])
            y2 = float(bbox["y2"])
            return x1, y1, x2, y2
        except (KeyError, TypeError, ValueError):
            return None
    if isinstance(bbox, (list, tuple)) and len(bbox) == 4:
        try:
            x1, y1, x2, y2 = [float(v) for v in bbox]
            return x1, y1, x2, y2
        except (TypeError, ValueError):
            return None
    return None


def clamp_bbox(x1: float, y1: float, x2: float, y2: float, width: int, height: int) -> Tuple[float, float, float, float] | None:
    x1 = max(0.0, min(float(width), x1))
    x2 = max(0.0, min(float(width), x2))
    y1 = max(0.0, min(float(height), y1))
    y2 = max(0.0, min(float(height), y2))
    if x2 <= x1 or y2 <= y1:
        return None
    return x1, y1, x2, y2


def bbox_to_yolo(bbox: Tuple[float, float, float, float], width: int, height: int) -> Tuple[float, float, float, float]:
    x1, y1, x2, y2 = bbox
    box_w = x2 - x1
    box_h = y2 - y1
    x_center = x1 + box_w / 2.0
    y_center = y1 + box_h / 2.0
    return (
        x_center / width,
        y_center / height,
        box_w / width,
        box_h / height,
    )


def yolo_line(class_id: int, values: Tuple[float, float, float, float]) -> str:
    x, y, w, h = values
    return f"{class_id} {x:.6f} {y:.6f} {w:.6f} {h:.6f}"


def copy_or_symlink(src: Path, dst: Path, mode: str) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    if mode == "symlink":
        dst.symlink_to(src.resolve())
    else:
        shutil.copy2(src, dst)


def split_pages(page_paths: List[Path], val_ratio: float, seed: int) -> Tuple[set[Path], set[Path]]:
    rng = random.Random(seed)
    paths = list(page_paths)
    rng.shuffle(paths)
    if len(paths) <= 1:
        return set(paths), set()
    val_count = max(1, int(round(len(paths) * val_ratio))) if val_ratio > 0 else 0
    val_count = min(val_count, len(paths) - 1)
    val_pages = set(paths[:val_count])
    train_pages = set(paths[val_count:])
    return train_pages, val_pages


def write_data_yaml(output_dir: Path, class_names: List[str]) -> None:
    # No PyYAML dependency needed.
    names_yaml = "\n".join([f"  {i}: {name}" for i, name in enumerate(class_names)])
    text = f"""# Auto-generated by tools/review_tools/export_review_to_yolo.py
path: {output_dir.resolve()}
train: images/train
val: images/val

nc: {len(class_names)}
names:
{names_yaml}
"""
    (output_dir / "data.yaml").write_text(text, encoding="utf-8")


def convert(project_root: Path, export_dir: Path, metadata_path: Path, output_dir: Path, class_names: List[str], val_ratio: float, seed: int, copy_mode: str, min_box_size: float) -> dict:
    class_to_id = {name: i for i, name in enumerate(class_names)}
    rows = list(read_jsonl(metadata_path))

    grouped: Dict[Path, List[dict]] = defaultdict(list)
    skipped = []
    for row in rows:
        cls = row.get("reviewed_type") or row.get("effective_type") or row.get("type")
        if cls not in class_to_id:
            skipped.append({"reason": "unknown_class", "class": cls, "crop_id": row.get("crop_id")})
            continue
        image_path = resolve_project_path(project_root, row.get("image_path"))
        if image_path is None or not image_path.exists():
            skipped.append({"reason": "missing_image", "image_path": row.get("image_path"), "crop_id": row.get("crop_id")})
            continue
        if parse_bbox(row) is None:
            skipped.append({"reason": "missing_or_invalid_bbox", "crop_id": row.get("crop_id")})
            continue
        grouped[image_path].append(row)

    output_dir.mkdir(parents=True, exist_ok=True)
    for sub in ["images/train", "images/val", "labels/train", "labels/val"]:
        (output_dir / sub).mkdir(parents=True, exist_ok=True)

    train_pages, val_pages = split_pages(list(grouped.keys()), val_ratio=val_ratio, seed=seed)

    counts_by_class = Counter()
    counts_by_split = Counter()
    written_images = 0
    written_labels = 0
    page_map = {}

    for page_index, image_path in enumerate(sorted(grouped.keys()), start=1):
        split = "val" if image_path in val_pages else "train"
        output_name = safe_image_name(image_path, page_index)
        out_img = output_dir / "images" / split / output_name
        out_lbl = output_dir / "labels" / split / f"{Path(output_name).stem}.txt"

        try:
            with Image.open(image_path) as img:
                width, height = img.size
        except Exception as exc:
            skipped.append({"reason": "cannot_open_image", "image_path": str(image_path), "error": str(exc)})
            continue

        label_lines = []
        for row in grouped[image_path]:
            cls = row.get("reviewed_type") or row.get("effective_type") or row.get("type")
            bbox = parse_bbox(row)
            if bbox is None:
                continue
            bbox = clamp_bbox(*bbox, width=width, height=height)
            if bbox is None:
                skipped.append({"reason": "empty_bbox_after_clamp", "crop_id": row.get("crop_id")})
                continue
            x1, y1, x2, y2 = bbox
            if (x2 - x1) < min_box_size or (y2 - y1) < min_box_size:
                skipped.append({"reason": "bbox_too_small", "crop_id": row.get("crop_id"), "bbox": [x1, y1, x2, y2]})
                continue
            class_id = class_to_id[cls]
            label_lines.append(yolo_line(class_id, bbox_to_yolo(bbox, width, height)))
            counts_by_class[cls] += 1
            counts_by_split[split] += 1

        if not label_lines:
            continue

        copy_or_symlink(image_path, out_img, copy_mode)
        out_lbl.write_text("\n".join(label_lines) + "\n", encoding="utf-8")
        written_images += 1
        written_labels += len(label_lines)
        page_map[str(image_path)] = {
            "split": split,
            "output_image": str(out_img),
            "output_label": str(out_lbl),
            "num_labels": len(label_lines),
        }

    write_data_yaml(output_dir, class_names)

    report = {
        "project_root": str(project_root),
        "export_dir": str(export_dir),
        "metadata_path": str(metadata_path),
        "output_dir": str(output_dir),
        "classes": class_names,
        "num_input_rows": len(rows),
        "num_grouped_pages": len(grouped),
        "num_written_images": written_images,
        "num_written_labels": written_labels,
        "counts_by_class": dict(counts_by_class),
        "counts_by_split": dict(counts_by_split),
        "num_skipped": len(skipped),
        "skipped_examples": skipped[:50],
        "copy_mode": copy_mode,
        "val_ratio": val_ratio,
        "seed": seed,
        "min_box_size": min_box_size,
    }
    (output_dir / "conversion_report.json").write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    (output_dir / "page_map.json").write_text(json.dumps(page_map, indent=2, ensure_ascii=False), encoding="utf-8")
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", default=".", help="Project root. Usually current directory.")
    parser.add_argument("--export-dir", required=True, help="Path to outputs/review_exports/export_YYYYMMDD_HHMMSS")
    parser.add_argument("--metadata", default=None, help="Metadata JSONL. Defaults to <export-dir>/exportable_metadata.jsonl")
    parser.add_argument("--output-dir", default="outputs/review_yolo_dataset")
    parser.add_argument("--classes", nargs="*", default=DEFAULT_CLASSES)
    parser.add_argument("--val-ratio", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--copy-mode", choices=["copy", "symlink"], default="copy")
    parser.add_argument("--min-box-size", type=float, default=2.0)
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    export_dir = (project_root / args.export_dir).resolve() if not Path(args.export_dir).is_absolute() else Path(args.export_dir).resolve()
    metadata_path = Path(args.metadata).resolve() if args.metadata else export_dir / "exportable_metadata.jsonl"
    output_dir = (project_root / args.output_dir).resolve() if not Path(args.output_dir).is_absolute() else Path(args.output_dir).resolve()

    report = convert(
        project_root=project_root,
        export_dir=export_dir,
        metadata_path=metadata_path,
        output_dir=output_dir,
        class_names=args.classes,
        val_ratio=args.val_ratio,
        seed=args.seed,
        copy_mode=args.copy_mode,
        min_box_size=args.min_box_size,
    )

    print("✅ YOLO dataset created")
    print(f"Output: {output_dir}")
    print(f"Images: {report['num_written_images']}")
    print(f"Labels: {report['num_written_labels']}")
    print(f"Classes: {report['counts_by_class']}")
    print(f"Skipped: {report['num_skipped']}")
    print(f"Data YAML: {output_dir / 'data.yaml'}")


if __name__ == "__main__":
    main()
