import argparse
import json
import shutil
from pathlib import Path

import faiss
import numpy as np


def load_embeddings(embeddings_path):
    """
    Carrega els embeddings en format .npy.

    Esperem una matriu NumPy de forma:
        (num_crops, embedding_dim)

    Exemple:
        (85, 13360)
    """
    embeddings = np.load(embeddings_path).astype(np.float32)

    if embeddings.ndim != 2:
        raise ValueError(f"Expected 2D embeddings array, got shape {embeddings.shape}")

    return embeddings


def l2_normalize_embeddings(embeddings, eps=1e-8):
    """
    Normalitza cada embedding perquè tingui norma 1.

    Això permet usar FAISS amb Inner Product com a similitud cosinus.
    Com que els vectors queden normalitzats:
        inner product ≈ cosine similarity
    """
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    norms = np.maximum(norms, eps)
    return embeddings / norms


def count_metadata_lines(metadata_path):
    """
    Compta quantes línies té el metadata.jsonl.

    Ha de coincidir amb el nombre d'embeddings.
    Si no coincideix, FAISS retornaria IDs que no corresponen bé al metadata.
    """
    metadata_path = Path(metadata_path)

    if not metadata_path.exists():
        raise FileNotFoundError(f"Metadata file not found: {metadata_path}")

    count = 0

    with metadata_path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                count += 1

    return count


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--embeddings",
        required=True,
        help="Path to embeddings.npy generated by build_embeddings.py",
    )

    parser.add_argument(
        "--metadata",
        required=True,
        help="Path to metadata.jsonl generated by build_embeddings.py",
    )

    parser.add_argument(
        "--output-dir",
        required=True,
        help="Folder where FAISS index and copied metadata will be saved",
    )

    parser.add_argument(
        "--index-name",
        default="visual_index.faiss",
        help="Output FAISS index filename",
    )

    parser.add_argument(
        "--metric",
        choices=["cosine", "l2"],
        default="cosine",
        help="Similarity metric. cosine is recommended for normalized embeddings.",
    )

    args = parser.parse_args()

    embeddings_path = Path(args.embeddings)
    metadata_path = Path(args.metadata)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Carregar embeddings.
    embeddings = load_embeddings(embeddings_path)

    num_embeddings, embedding_dim = embeddings.shape

    # 2. Comprovar que metadata i embeddings tenen la mateixa longitud.
    metadata_count = count_metadata_lines(metadata_path)

    if metadata_count != num_embeddings:
        raise ValueError(
            f"Metadata count ({metadata_count}) does not match "
            f"number of embeddings ({num_embeddings})"
        )

    # 3. Crear índex FAISS.
    if args.metric == "cosine":
        # Per cosinus, normalitzem i usem Inner Product.
        embeddings_for_index = l2_normalize_embeddings(embeddings)
        index = faiss.IndexFlatIP(embedding_dim)
    else:
        # Per distància L2 clàssica.
        embeddings_for_index = embeddings
        index = faiss.IndexFlatL2(embedding_dim)

    # 4. Afegir vectors a l'índex.
    index.add(embeddings_for_index)

    # 5. Guardar l'índex.
    index_path = output_dir / args.index_name
    faiss.write_index(index, str(index_path))

    # 6. Copiar metadata al costat de l'índex.
    copied_metadata_path = output_dir / "metadata.jsonl"
    shutil.copy2(metadata_path, copied_metadata_path)

    # 7. Guardar config per reproduïbilitat.
    config = {
        "embeddings": str(embeddings_path),
        "metadata": str(metadata_path),
        "index_path": str(index_path),
        "metric": args.metric,
        "num_embeddings": int(num_embeddings),
        "embedding_dim": int(embedding_dim),
        "faiss_index_type": type(index).__name__,
    }

    config_path = output_dir / "faiss_config.json"

    with config_path.open("w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"Saved FAISS index: {index_path}")
    print(f"Saved metadata:    {copied_metadata_path}")
    print(f"Saved config:      {config_path}")
    print(f"Index vectors:     {index.ntotal}")
    print(f"Embedding dim:     {embedding_dim}")
    print(f"Metric:            {args.metric}")


if __name__ == "__main__":
    main()
