#!/usr/bin/env python3
import argparse
import json
import random
import shutil
import subprocess
from pathlib import Path


IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}


def collect_images(source_pages):
    """Agafa imatges d'una o diverses carpetes."""
    images = []

    for folder in source_pages:
        folder = Path(folder)

        if not folder.exists():
            raise FileNotFoundError(f"Source pages folder not found: {folder}")

        for path in sorted(folder.rglob("*")):
            if path.suffix.lower() in IMAGE_EXTENSIONS:
                images.append(path)

    return images


def safe_link_or_copy(src, dst, mode):
    """Crea symlink o còpia sense duplicar feina si ja existeix."""
    dst.parent.mkdir(parents=True, exist_ok=True)

    if dst.exists() or dst.is_symlink():
        return

    if mode == "copy":
        shutil.copy2(src, dst)
    else:
        dst.symlink_to(src.resolve())


def prepare_batch_pages(images, pages_dir, mode):
    """
    Crea la carpeta pages del batch.

    Per defecte usem symlink per no copiar GBs.
    Si hi ha noms duplicats, afegim prefix numèric.
    """
    pages_dir.mkdir(parents=True, exist_ok=True)

    used_names = set()
    batch_images = []

    for i, src in enumerate(images):
        name = src.name

        if name in used_names:
            name = f"{i:06d}_{src.name}"

        used_names.add(name)

        dst = pages_dir / name
        safe_link_or_copy(src, dst, mode=mode)
        batch_images.append(dst)

    return batch_images


def run_command(cmd):
    """Executa una comanda i falla si hi ha error."""
    print()
    print("Running:")
    print(" ".join(str(x) for x in cmd))
    print()

    subprocess.run(cmd, check=True)


def write_batch_manifest(batch_images, manifest_path, batch_id):
    """Guarda manifest simple del batch."""
    manifest_path.parent.mkdir(parents=True, exist_ok=True)

    with manifest_path.open("w", encoding="utf-8") as f:
        for i, path in enumerate(batch_images):
            row = {
                "batch_id": batch_id,
                "page_index": i,
                "image": path.name,
                "image_path": str(path),
            }
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_batch_config(args, batch_dir, batch_images):
    """Escriu config completa del batch."""
    batch_config = {
        "batch_id": args.batch_id,
        "description": args.description,
        "source_pages": [str(Path(p)) for p in args.source_pages],
        "batch_pages": str(batch_dir / "pages"),
        "batch_manifest": str(batch_dir / "batch_manifest.jsonl"),
        "predicted_layouts": str(batch_dir / "predicted_layouts"),
        "crop_dir": str(batch_dir / "object_crops"),
        "metadata": str(batch_dir / "object_crops" / "metadata.jsonl"),
        "review_log": str(batch_dir / "review_log.jsonl"),
        "weights": args.weights,
        "confidence": args.conf,
        "imgsz": args.imgsz,
        "classes": args.classes,
        "crop": {
            "padding": args.padding,
            "min_width": args.min_width,
            "min_height": args.min_height,
        },
        "faiss_dir": "outputs/faiss/current",
        "faiss_tmp_dir": "outputs/faiss/current_build_tmp",
        "vae_dir": "outputs/faiss/vae/global",
        "vae_model": args.vae_model,
        "index_output_dir": "outputs/index",
        "page_count": len(batch_images),
        "copy_mode": args.copy_mode,
        "notes": [
            "This config was generated by tools/pipeline/build_review_batch.py.",
            "The detector can only predict classes supported by the selected weights.",
            "FAISS should be rebuilt from metadata crop_path values to include manual crops.",
        ],
    }

    config_path = batch_dir / "batch_config.json"
    config_path.write_text(
        json.dumps(batch_config, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    configs_dir = Path("configs")
    configs_dir.mkdir(parents=True, exist_ok=True)

    named_config = configs_dir / f"{args.batch_id}.json"
    named_config.write_text(
        json.dumps(batch_config, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    if args.set_current:
        current_config = configs_dir / "review_current.json"
        current_config.write_text(
            json.dumps(batch_config, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    print()
    print(f"Batch config: {config_path}")
    print(f"Named config: {named_config}")

    if args.set_current:
        print("Current config updated: configs/review_current.json")


def main():
    parser = argparse.ArgumentParser(
        description="Build a review batch from one or more local page folders."
    )

    parser.add_argument("--batch-id", required=True)
    parser.add_argument("--description", default="Review batch")

    parser.add_argument(
        "--source-pages",
        nargs="+",
        required=True,
        help="One or more folders containing .jpg/.png/.webp page images.",
    )

    parser.add_argument(
        "--max-pages",
        type=int,
        default=None,
        help="Optional number of pages to sample.",
    )

    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument(
        "--copy-mode",
        choices=["symlink", "copy"],
        default="symlink",
        help="Use symlinks by default to avoid duplicating large datasets.",
    )

    parser.add_argument(
        "--weights",
        default="runs/detect/layout_detector_typewritten_v1/weights/best.pt",
        help="YOLO weights to use.",
    )

    parser.add_argument("--conf", type=float, default=0.30)
    parser.add_argument("--imgsz", type=int, default=1024)

    parser.add_argument(
        "--classes",
        nargs="+",
        default=["stamp", "handwritten_text", "crossout", "typewritten_text"],
        help="Classes to crop if detected by the model.",
    )

    parser.add_argument("--padding", type=int, default=8)
    parser.add_argument("--min-width", type=int, default=20)
    parser.add_argument("--min-height", type=int, default=20)

    parser.add_argument(
        "--vae-model",
        default="outputs/vae/vae_best.pt",
    )

    parser.add_argument(
        "--output-root",
        default="outputs/batches",
    )

    parser.add_argument(
        "--set-current",
        action="store_true",
        help="Also write configs/review_current.json for current scripts.",
    )

    parser.add_argument(
        "--skip-inference",
        action="store_true",
        help="Only prepare pages/config, do not run detector.",
    )

    parser.add_argument(
        "--skip-crops",
        action="store_true",
        help="Run/keep predictions but skip crop generation.",
    )

    args = parser.parse_args()

    random.seed(args.seed)

    batch_dir = Path(args.output_root) / args.batch_id
    pages_dir = batch_dir / "pages"
    layouts_dir = batch_dir / "predicted_layouts"
    crops_dir = batch_dir / "object_crops"
    review_log = batch_dir / "review_log.jsonl"

    batch_dir.mkdir(parents=True, exist_ok=True)

    images = collect_images(args.source_pages)

    if args.max_pages is not None and len(images) > args.max_pages:
        images = random.sample(images, args.max_pages)
        images = sorted(images)

    print(f"Input images selected: {len(images)}")

    batch_images = prepare_batch_pages(
        images=images,
        pages_dir=pages_dir,
        mode=args.copy_mode,
    )

    write_batch_manifest(
        batch_images=batch_images,
        manifest_path=batch_dir / "batch_manifest.jsonl",
        batch_id=args.batch_id,
    )

    review_log.touch(exist_ok=True)

    if not args.skip_inference:
        run_command([
            "python",
            "detection/stamp_detection/infer_yolo_layout_json.py",
            "--weights",
            args.weights,
            "--input",
            str(pages_dir),
            "--output",
            str(layouts_dir),
            "--conf",
            str(args.conf),
            "--imgsz",
            str(args.imgsz),
            "--document-prefix",
            args.batch_id,
        ])

    if not args.skip_crops:
        run_command([
            "python",
            "processing/crop_objects_from_layout.py",
            "--layouts",
            str(layouts_dir),
            "--images",
            str(pages_dir),
            "--output",
            str(crops_dir),
            "--classes",
            *args.classes,
            "--padding",
            str(args.padding),
            "--min-width",
            str(args.min_width),
            "--min-height",
            str(args.min_height),
            "--crop-id-prefix",
            args.batch_id,
        ])

    write_batch_config(args, batch_dir=batch_dir, batch_images=batch_images)

    print()
    print("Done.")
    print(f"Batch dir: {batch_dir}")
    print(f"Review log: {review_log}")


if __name__ == "__main__":
    main()
